name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: ['28']

    container:
      image: erlang:${{ matrix.erlang }}-alpine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        # Install curl and other essential tools for erlang.mk
        apk update
        apk add --no-cache \
          curl \
          git \
          build-base \
          openssl-dev \
          ncurses-dev

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
          .erlang.mk
        key: deps-${{ runner.os }}-${{ matrix.erlang }}-${{ hashFiles('Makefile') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.erlang }}-
          deps-${{ runner.os }}-

    - name: Download dependencies
      run: make deps

    - name: Compile project
      run: make app

    - name: Run tests
      run: make test

    - name: Run linting (if available)
      continue-on-error: true
      run: make elvis

    - name: Run static analysis (if available)
      continue-on-error: true
      run: make dialyzep

    - name: Run release
      run: make release

  build:
    runs-on: ubuntu-latest
    needs: compile-and-test
    steps:
      - name: Beam Docker Release
        uses: shortishly/beam-docker-release-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build-image: erlang:28
          build-platforms: linux/amd64
          build-tags: ghcr.io/${{ github.repository }}:erlang.mk
